### ISSUE TITLE
Topology install errors with commit a7852e0

### ISSUE THREAD

**Issue by paulmcauley** [WeirdTreeThing/chromebook-linux-audio#113]
With commit a7852e0 ("avs: install topology package from upstream repo", 2024-03-21) I get the following:

```
paul@localhost:~/chromebook-linux-audio> ./setup-audio --force-avs-install
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing AVS
WARNING: Your device has max98357a and can cause permanent damage to your speakers if you set the volume too loud!
Type "I understand the risk of permanently damaging my speakers" in all caps to continue: I UNDERSTAND THE RISK OF PERMANENTLY DAMAGING MY SPEAKERS
Installing topology
tar: This does not look like a tar archive
tar: Skipping to next header
gzip: stdin has more than one entry--rest ignored
tar: Child returned status 2
tar: Error is not recoverable: exiting now
failed to run command: tar xf /tmp/avs_tplg/avs-tplg.tar.gz -C /tmp/avs_tplg
Traceback (most recent call last):
  File "/home/paul/chromebook-linux-audio/./setup-audio", line 301, in <module>
    match_platform(board)
  File "/home/paul/chromebook-linux-audio/./setup-audio", line 94, in match_platform
    avs_audio()
  File "/home/paul/chromebook-linux-audio/./setup-audio", line 153, in avs_audio
    cpdir("/tmp/avs_tplg/avs-topology/lib/firmware/intel/avs", "/lib/firmware/intel/avs")
  File "/home/paul/chromebook-linux-audio/functions.py", line 89, in cpdir
    raise FileNotFoundError(f"No such directory: {src_as_path.absolute().as_posix()}")
FileNotFoundError: No such directory: /tmp/avs_tplg/avs-topology/lib/firmware/intel/avs

```

Hardware: Lenovo Yoga Chromebook C630 (Pantheon)

Software:
Operating System: openSUSE Tumbleweed 20240320
KDE Plasma Version: 6.0.80
KDE Frameworks Version: 6.1.0
Qt Version: 6.6.2
Kernel Version: 6.8.1-1-default (64-bit)
Graphics Platform: Wayland
Processors: 8 × Intel® Core™ i7-8550U CPU @ 1.80GHz
Memory: 15.5 GiB of RAM
Graphics Processor: Mesa Intel® UHD Graphics 620
Manufacturer: Google
Product Name: Pantheon
System Version: 1.0

**Comment by WeirdTreeThing** [comment]
Whoops, I somehow missed that. Try it now.

**Comment by WeirdTreeThing** [comment]
By the way, thank you for making good bug reports. Not only did you fill out the template, but you provided even more info.

**Comment by paulmcauley** [comment]
Thank you, is working now
