### ISSUE TITLE
setup audio script fails

### ISSUE THREAD

**Issue by uh410error** [WeirdTreeThing/chromebook-linux-audio#126]
**Describe the bug**
Script fails with most recent commit 334ae78

**Boardname**
Shyvana (Asus C434T)

**Other**
Fedora 40 (Workstation edition)
GNOME v. 46
Wayland
Kernal v. 6.8.7-300.fc40.x86_64

**Output**

```
sam@fedora:~/chromebook-linux-audio$ ./setup-audio 
[sudo] password for sam: 
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing AVS
Installing topology
Installing modprobe config
Forcing avs_dmic to use S16LE format
Traceback (most recent call last):
  File "/home/sam/chromebook-linux-audio/./setup-audio", line 318, in <module>
    match_platform(board)
  File "/home/sam/chromebook-linux-audio/./setup-audio", line 94, in match_platform
    avs_audio()
  File "/home/sam/chromebook-linux-audio/./setup-audio", line 168, in avs_audio
    cpfile("conf/common/51-avs-dmic.conf", "/etc/wireplumber/wireplumber.conf.d/51-avs-dmic.conf")
  File "/home/sam/chromebook-linux-audio/functions.py", line 77, in cpfile
    raise FileNotFoundError(f"No such file: {src_as_path.absolute().as_posix()}")
FileNotFoundError: No such file: /home/sam/chromebook-linux-audio/conf/common/51-avs-dmic.conf
sam@fedora:~/chromebook-linux-audio$

```

**Comment by WeirdTreeThing** [comment]
see if it works now

**Comment by uh410error** [comment]
Yep that fixed it! Rebooted and tested - sound is good. Thank you so much!
