### ISSUE TITLE
[Question] Alpine Linux Support?

### ISSUE THREAD

**Issue by HeteroChromia420** [WeirdTreeThing/chromebook-linux-audio#143]
Figured to ask: Has this utility been tested on Alpine Linux? if yes, is it compatible with it? if not, would you be interested in having someone testing it?

**Comment by HeteroChromia420** [comment]
went to check, it is indeed compatible, just not listed apparently...

**Comment by kkilobyte** [comment]
Might? More like is....

```~/chromebook-linux-audio $ ./setup-audio
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Apollolake has two audio drivers:
SOF: Stable but doesn't work with headphones.
AVS: Unstable and can cause damage to speakers but supports all audio hardware.
NOTE: Speakers are disabled on AVS as a safety precaution. (use --force-avs-install to override)Your speakers will still work on SOF though.
Which driver would you like to use? [sof/avs]: sof
Using sof
Installing SOF
Installing SOF firmware
Unknown package manager! Please install sof-firmware using your package manager.
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1297, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 1297 (delta 170), reused 306 (delta 163), pack-reused 976
Receiving objects: 100% (1297/1297), 222.23 KiB | 928.00 KiB/s, done.
Resolving deltas: 100% (657/657), done.
Traceback (most recent call last):
  File "/home/kilo/chromebook-linux-audio/./setup-audio", line 322, in <module>
    install_ucm()
  File "/home/kilo/chromebook-linux-audio/./setup-audio", line 40, in install_ucm
    cpdir(f"/tmp/chromebook-ucm-conf/{platform}", "/usr/share/alsa/ucm2/conf.d")
  File "/home/kilo/chromebook-linux-audio/functions.py", line 65, in cpdir
    mkdir(dst_as_string)
  File "/home/kilo/chromebook-linux-audio/functions.py", line 52, in mkdir
    mk_dir_as_path.mkdir(parents=create_parents)
  File "/usr/lib/python3.12/pathlib.py", line 1311, in mkdir
    os.mkdir(self, mode)
FileNotFoundError: [Errno 2] No such file or directory: '/usr/share/alsa/ucm2/conf.d'

~/chromebook-linux-audio $ doas apk add sof-firmware
(1/1) Installing sof-firmware (2024.03-r1)
OK: 3246 MiB in 753 packages

~/chromebook-linux-audio $ doas apk add alsa-ucm-conf
(1/1) Installing alsa-ucm-conf (1.2.11-r1)
OK: 3249 MiB in 754 packages

~/chromebook-linux-audio $ doas ./setup-audio
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Apollolake has two audio drivers:
SOF: Stable but doesn't work with headphones.
AVS: Unstable and can cause damage to speakers but supports all audio hardware.
NOTE: Speakers are disabled on AVS as a safety precaution. (use --force-avs-install to override)Your speakers will still work on SOF though.
Which driver would you like to use? [sof/avs]: sof
Using sof
Installing SOF
Installing UCM configuration
Cloning into '/tmp/chromebook-ucm-conf'...
remote: Enumerating objects: 1297, done.
remote: Counting objects: 100% (321/321), done.
remote: Compressing objects: 100% (136/136), done.
remote: Total 1297 (delta 170), reused 306 (delta 163), pack-reused 976
Receiving objects: 100% (1297/1297), 222.23 KiB | 655.00 KiB/s, done.
Resolving deltas: 100% (657/657), done.
Increasing alsa headroom (fixes instability)
Audio installed successfully! Reboot to finish setup.
~/chromebook-linux-audio $ ```

Works flawlessly after installing both `alsa-ucm-conf` and `sof-firmware` using `doas apk add sof-firmware alsa-ucm-conf`.

**Comment by WeirdTreeThing** [comment]
Support for apk has been added
