### ISSUE TITLE
Won't Install, Returns Python Error In Terminal.

### ISSUE THREAD

**Issue by ZenDeuo** [WeirdTreeThing/chromebook-linux-audio#166]
**Describe the bug**
When I run ./setup-audio, it runs and then stops and returns "urllib.error.HTTPError: HTTP Error 404: Not Found"

**Boardname**
If you don't know where to find this, run `cat /sys/class/dmi/id/product_name`
Rammus

**Logs**
Generate logs with `wget https://raw.githubusercontent.com/chrultrabook/linux-tools/main/debugging.sh; bash debugging.sh` and attach the output here.

❯ ./setup-audio                                                                                       
WARNING: You may run into audio issues, even after running this script. Please report any issues on github.
Installing AVS
Installing topology
Traceback (most recent call last):
  File "/home/deuo/chromebook-linux-audio/./setup-audio", line 319, in <module>
    match_platform(board)
  File "/home/deuo/chromebook-linux-audio/./setup-audio", line 95, in match_platform
    avs_audio()
  File "/home/deuo/chromebook-linux-audio/./setup-audio", line 151, in avs_audio
    urlretrieve(url=avs_tplg_url, filename="/tmp/avs_tplg/avs-tplg.tar.gz")
  File "/usr/lib64/python3.12/urllib/request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 521, in open
    response = meth(req, response)
               ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 630, in http_response
    response = self.parent.error(
               ^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 559, in error
    return self._call_chain(*args)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "/usr/lib64/python3.12/urllib/request.py", line 639, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

Here's The Debugger tar.gz:
[debug-logs-Rammus-2024-09-01_03h31m.tar.gz](https://github.com/user-attachments/files/16827070/debug-logs-Rammus-2024-09-01_03h31m.tar.gz)

**Comment by ZenDeuo** [comment]
Thank you Koluckirafal. I'll look into that work around now :)
